import type { TileTypeId } from '@mahjong-mcr/engine'
import { FlowerTileFace } from './FlowerTileFace.js'
import { tileImageSrc } from './tileImages.js'

export interface TileFaceContentProps {
  typeId: TileTypeId
}

// The inner content of a tile box — never a wrapper div of its own, so
// every call site keeps its own existing wrapper (data-testid, role,
// onClick/pointer handlers) untouched. Renders the real tile-face SVG when
// one exists — all 42 tile types do (34 standard, generated by
// scripts/generate-tile-art.mjs from a CC0 source; 8 flower/season, the
// same script's original hand-coded artwork — see THIRD_PARTY_LICENSES.md).
// FlowerTileFace is kept as the fallback path (not normally reachable,
// since tileImageSrc now resolves every real TileTypeId) rather than
// deleted, so a missing/misnamed asset degrades to a real distinct face
// instead of a blank box.
//
// The image/SVG stays visually decorative and the sr-only span carries the
// accessible name instead, so screen readers aren't double-announced.
// Text-content-based test assertions (`toHaveTextContent(typeId)`) keep
// working unchanged as a result — .textContent includes visually-hidden
// text nodes regardless of CSS.
export function TileFaceContent({ typeId }: TileFaceContentProps) {
  const src = tileImageSrc(typeId)
  return (
    <>
      {src ? (
        <img src={src} alt="" draggable={false} className="pointer-events-none h-full w-full select-none object-contain" />
      ) : (
        <FlowerTileFace typeId={typeId} />
      )}
      <span className="sr-only">{typeId}</span>
    </>
  )
}
